//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/GameInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @GameInputs: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @GameInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""GameInputs"",
    ""maps"": [
        {
            ""name"": ""Camera"",
            ""id"": ""64ad9aad-2e92-46a9-8394-8d00d4d16a2d"",
            ""actions"": [
                {
                    ""name"": ""Yaw"",
                    ""type"": ""Value"",
                    ""id"": ""936e18bb-43ca-46dd-a0ca-619b13d87363"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Pitch"",
                    ""type"": ""Value"",
                    ""id"": ""c3151924-eaf4-4b82-b51f-6b5ab98ab78f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RTSView"",
                    ""type"": ""Button"",
                    ""id"": ""30f30e9e-c968-4b1b-bce3-0617028eb131"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""7af0d80b-4936-4dda-8dd4-1ba6dc3ee4a2"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TouchUpAndDown"",
                    ""type"": ""Value"",
                    ""id"": ""3107315d-2312-4d7a-9776-9aacf992b476"",
                    ""expectedControlType"": ""Vector3"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""7bbfbee4-42a0-4158-a3b8-e7409d3a91f5"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""74e0dcb8-042d-4fc3-8e6a-db7ce77e4bb9"",
                    ""path"": ""<Keyboard>/#(Z)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""ceac0d04-73a8-4c01-ad4e-6e5eeb949215"",
                    ""path"": ""<Keyboard>/#(X)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fbf31bdc-3319-4a70-8f20-b5dac3d1ff24"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pitch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9dc1e153-ab93-4fd3-913e-98ad334ca781"",
                    ""path"": ""<Keyboard>/#(C)"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RTSView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""65d45da1-04ed-41b5-aec7-d37b7b660994"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f675fff4-5c88-449b-8b07-ff6e1889137f"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b1273491-306b-45bd-94d2-9191081f3594"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""fad6134a-de3c-49d5-8cb2-bd19ddcaadfd"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Yaw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""24039fbf-a13f-4dcc-8333-44e65fcbe867"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e9edc7a8-387c-49f7-9633-520b36ed5e60"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""bbeb36d7-9cfc-485f-875a-c577ea1b548b"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""be1132c5-eca0-481d-8c70-5ddfa9416641"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""c38d19e4-0e90-4a95-990b-b5ec25ba6093"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""8be72e94-9b10-4e94-aecf-db79ff448464"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""7a18b97e-38c1-431e-a8dd-a54e91bec5af"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""53f89628-ca8b-498b-8f98-5c44805eb9a1"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""21898b89-b0ab-46ab-8990-5f09ada78e7d"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""7933b512-b20b-4704-898d-f2fd57b0a50b"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""38947bf8-0718-4171-97f8-019fbe2451ec"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""60e5e9b8-135f-4bcf-9b73-55f5e2c1a87d"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""f464387a-e5ed-4bb4-b33b-5a5b8353c5ea"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""0c77278a-34e6-4453-a3ab-8d842bc21daa"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""3D Vector"",
                    ""id"": ""3d8934ab-7809-4db5-b25a-355939c1791b"",
                    ""path"": ""3DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchUpAndDown"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f99c2895-e177-4aca-aba4-b3f3c00ede40"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchUpAndDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b9832216-22ea-4c36-b564-73aa3725028f"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchUpAndDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""490b53df-cb80-470c-a09c-7b3d9032e6be"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchUpAndDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""aff717cc-ba85-4d25-b7e9-f7f9a58ffc3a"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchUpAndDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""forward"",
                    ""id"": ""20dcf2be-bab7-4dc8-ae05-ced6cda67bc0"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchUpAndDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""backward"",
                    ""id"": ""84b53ec3-16ae-46ad-b98d-56174f526281"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchUpAndDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        },
        {
            ""name"": ""Entities"",
            ""id"": ""e0cb311d-e2e6-4df9-b740-3f0744b6e30f"",
            ""actions"": [
                {
                    ""name"": ""Speed"",
                    ""type"": ""Value"",
                    ""id"": ""e7f4dcc5-9419-4c2b-9803-ef5d77e6b62b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Heading"",
                    ""type"": ""Button"",
                    ""id"": ""0e87d360-2831-406f-b5d0-2e41f038436c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextEntity"",
                    ""type"": ""Button"",
                    ""id"": ""1042ff9a-e152-4c5c-9ab5-67fa312a8108"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cursor"",
                    ""type"": ""Button"",
                    ""id"": ""23315e56-a9ea-4e8c-a437-fe05d8f2f96f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CursorPosition"",
                    ""type"": ""Value"",
                    ""id"": ""6ffc726c-0a1b-4ceb-92ac-c6d50126b73e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClearSelection"",
                    ""type"": ""Button"",
                    ""id"": ""b786c702-b76e-4a3b-8944-eceddd711fa5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Button"",
                    ""id"": ""0ebc5105-0eb8-4e9e-9509-eac657353e45"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Intercept"",
                    ""type"": ""Button"",
                    ""id"": ""1e3d25fb-140b-48ac-8912-414bc32e6851"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Create100"",
                    ""type"": ""Button"",
                    ""id"": ""33b05981-4125-4b96-ab6c-8931622d5dfe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""2f26b6b2-8caa-47ae-9d34-60164ca9fc92"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speed"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""0b083da9-c3ae-44b9-9864-43808637cc13"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0543b90a-cf78-4ccb-b103-3663ed4a3437"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Speed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f9c260ba-667f-47e8-8698-66891e9e0383"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heading"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""cba0068e-928b-4f67-ac0c-fca0e8c05da5"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heading"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""9458b161-f52b-488b-8fa1-1e0626ab87ed"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Heading"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b4fc5811-d167-4f6e-8a48-cb505b5b84c6"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextEntity"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e27d141a-4f89-4ab9-a808-440835f71db7"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClearSelection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e15eb431-31fc-4173-be3b-3f74f80c60bb"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Intercept"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1a2a1ca2-150f-4631-b88a-d09e2d2a743c"",
                    ""path"": ""<Keyboard>/f12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Create100"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49d9dc12-6aaf-4947-b406-5bbd5c11bdf4"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42f0394a-92c9-4ca2-b1ce-bdc7b8b1463d"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CursorPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""838e1eea-12c1-4b52-814b-e2dc05fc21b4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10c3842b-c577-4763-b6d2-4ddbfb31dcc2"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": ""MultiTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6dfa7d76-3a90-414e-aa71-a944b02024b6"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""SlowTap"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6c7a5d93-ef0a-45f7-ad8b-0c3dc96635a4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Graph"",
            ""id"": ""82cfeebb-0cbe-4a27-a4ec-f1148e82249c"",
            ""actions"": [
                {
                    ""name"": ""Create"",
                    ""type"": ""Button"",
                    ""id"": ""9ced0b57-0c0d-4625-a297-5938cd1f00da"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Destroy"",
                    ""type"": ""Button"",
                    ""id"": ""31d1d784-59a6-4088-aafd-c2c1faf15f77"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""74c7c04c-ca52-4b6a-8432-9aedceb34e7a"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Create"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a5c9680-911d-4edb-a21c-ead802fc8d5d"",
                    ""path"": ""<Touchscreen>/primaryTouch/tap"",
                    ""interactions"": ""MultiTap(tapCount=3)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Create"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b8e9f9b-982d-43fa-ba17-c17c4068a660"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Destroy"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Camera
        m_Camera = asset.FindActionMap("Camera", throwIfNotFound: true);
        m_Camera_Yaw = m_Camera.FindAction("Yaw", throwIfNotFound: true);
        m_Camera_Pitch = m_Camera.FindAction("Pitch", throwIfNotFound: true);
        m_Camera_RTSView = m_Camera.FindAction("RTSView", throwIfNotFound: true);
        m_Camera_Movement = m_Camera.FindAction("Movement", throwIfNotFound: true);
        m_Camera_TouchUpAndDown = m_Camera.FindAction("TouchUpAndDown", throwIfNotFound: true);
        // Entities
        m_Entities = asset.FindActionMap("Entities", throwIfNotFound: true);
        m_Entities_Speed = m_Entities.FindAction("Speed", throwIfNotFound: true);
        m_Entities_Heading = m_Entities.FindAction("Heading", throwIfNotFound: true);
        m_Entities_NextEntity = m_Entities.FindAction("NextEntity", throwIfNotFound: true);
        m_Entities_Cursor = m_Entities.FindAction("Cursor", throwIfNotFound: true);
        m_Entities_CursorPosition = m_Entities.FindAction("CursorPosition", throwIfNotFound: true);
        m_Entities_ClearSelection = m_Entities.FindAction("ClearSelection", throwIfNotFound: true);
        m_Entities_Move = m_Entities.FindAction("Move", throwIfNotFound: true);
        m_Entities_Intercept = m_Entities.FindAction("Intercept", throwIfNotFound: true);
        m_Entities_Create100 = m_Entities.FindAction("Create100", throwIfNotFound: true);
        // Graph
        m_Graph = asset.FindActionMap("Graph", throwIfNotFound: true);
        m_Graph_Create = m_Graph.FindAction("Create", throwIfNotFound: true);
        m_Graph_Destroy = m_Graph.FindAction("Destroy", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Camera
    private readonly InputActionMap m_Camera;
    private List<ICameraActions> m_CameraActionsCallbackInterfaces = new List<ICameraActions>();
    private readonly InputAction m_Camera_Yaw;
    private readonly InputAction m_Camera_Pitch;
    private readonly InputAction m_Camera_RTSView;
    private readonly InputAction m_Camera_Movement;
    private readonly InputAction m_Camera_TouchUpAndDown;
    public struct CameraActions
    {
        private @GameInputs m_Wrapper;
        public CameraActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Yaw => m_Wrapper.m_Camera_Yaw;
        public InputAction @Pitch => m_Wrapper.m_Camera_Pitch;
        public InputAction @RTSView => m_Wrapper.m_Camera_RTSView;
        public InputAction @Movement => m_Wrapper.m_Camera_Movement;
        public InputAction @TouchUpAndDown => m_Wrapper.m_Camera_TouchUpAndDown;
        public InputActionMap Get() { return m_Wrapper.m_Camera; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CameraActions set) { return set.Get(); }
        public void AddCallbacks(ICameraActions instance)
        {
            if (instance == null || m_Wrapper.m_CameraActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CameraActionsCallbackInterfaces.Add(instance);
            @Yaw.started += instance.OnYaw;
            @Yaw.performed += instance.OnYaw;
            @Yaw.canceled += instance.OnYaw;
            @Pitch.started += instance.OnPitch;
            @Pitch.performed += instance.OnPitch;
            @Pitch.canceled += instance.OnPitch;
            @RTSView.started += instance.OnRTSView;
            @RTSView.performed += instance.OnRTSView;
            @RTSView.canceled += instance.OnRTSView;
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @TouchUpAndDown.started += instance.OnTouchUpAndDown;
            @TouchUpAndDown.performed += instance.OnTouchUpAndDown;
            @TouchUpAndDown.canceled += instance.OnTouchUpAndDown;
        }

        private void UnregisterCallbacks(ICameraActions instance)
        {
            @Yaw.started -= instance.OnYaw;
            @Yaw.performed -= instance.OnYaw;
            @Yaw.canceled -= instance.OnYaw;
            @Pitch.started -= instance.OnPitch;
            @Pitch.performed -= instance.OnPitch;
            @Pitch.canceled -= instance.OnPitch;
            @RTSView.started -= instance.OnRTSView;
            @RTSView.performed -= instance.OnRTSView;
            @RTSView.canceled -= instance.OnRTSView;
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @TouchUpAndDown.started -= instance.OnTouchUpAndDown;
            @TouchUpAndDown.performed -= instance.OnTouchUpAndDown;
            @TouchUpAndDown.canceled -= instance.OnTouchUpAndDown;
        }

        public void RemoveCallbacks(ICameraActions instance)
        {
            if (m_Wrapper.m_CameraActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICameraActions instance)
        {
            foreach (var item in m_Wrapper.m_CameraActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CameraActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CameraActions @Camera => new CameraActions(this);

    // Entities
    private readonly InputActionMap m_Entities;
    private List<IEntitiesActions> m_EntitiesActionsCallbackInterfaces = new List<IEntitiesActions>();
    private readonly InputAction m_Entities_Speed;
    private readonly InputAction m_Entities_Heading;
    private readonly InputAction m_Entities_NextEntity;
    private readonly InputAction m_Entities_Cursor;
    private readonly InputAction m_Entities_CursorPosition;
    private readonly InputAction m_Entities_ClearSelection;
    private readonly InputAction m_Entities_Move;
    private readonly InputAction m_Entities_Intercept;
    private readonly InputAction m_Entities_Create100;
    public struct EntitiesActions
    {
        private @GameInputs m_Wrapper;
        public EntitiesActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Speed => m_Wrapper.m_Entities_Speed;
        public InputAction @Heading => m_Wrapper.m_Entities_Heading;
        public InputAction @NextEntity => m_Wrapper.m_Entities_NextEntity;
        public InputAction @Cursor => m_Wrapper.m_Entities_Cursor;
        public InputAction @CursorPosition => m_Wrapper.m_Entities_CursorPosition;
        public InputAction @ClearSelection => m_Wrapper.m_Entities_ClearSelection;
        public InputAction @Move => m_Wrapper.m_Entities_Move;
        public InputAction @Intercept => m_Wrapper.m_Entities_Intercept;
        public InputAction @Create100 => m_Wrapper.m_Entities_Create100;
        public InputActionMap Get() { return m_Wrapper.m_Entities; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EntitiesActions set) { return set.Get(); }
        public void AddCallbacks(IEntitiesActions instance)
        {
            if (instance == null || m_Wrapper.m_EntitiesActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_EntitiesActionsCallbackInterfaces.Add(instance);
            @Speed.started += instance.OnSpeed;
            @Speed.performed += instance.OnSpeed;
            @Speed.canceled += instance.OnSpeed;
            @Heading.started += instance.OnHeading;
            @Heading.performed += instance.OnHeading;
            @Heading.canceled += instance.OnHeading;
            @NextEntity.started += instance.OnNextEntity;
            @NextEntity.performed += instance.OnNextEntity;
            @NextEntity.canceled += instance.OnNextEntity;
            @Cursor.started += instance.OnCursor;
            @Cursor.performed += instance.OnCursor;
            @Cursor.canceled += instance.OnCursor;
            @CursorPosition.started += instance.OnCursorPosition;
            @CursorPosition.performed += instance.OnCursorPosition;
            @CursorPosition.canceled += instance.OnCursorPosition;
            @ClearSelection.started += instance.OnClearSelection;
            @ClearSelection.performed += instance.OnClearSelection;
            @ClearSelection.canceled += instance.OnClearSelection;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Intercept.started += instance.OnIntercept;
            @Intercept.performed += instance.OnIntercept;
            @Intercept.canceled += instance.OnIntercept;
            @Create100.started += instance.OnCreate100;
            @Create100.performed += instance.OnCreate100;
            @Create100.canceled += instance.OnCreate100;
        }

        private void UnregisterCallbacks(IEntitiesActions instance)
        {
            @Speed.started -= instance.OnSpeed;
            @Speed.performed -= instance.OnSpeed;
            @Speed.canceled -= instance.OnSpeed;
            @Heading.started -= instance.OnHeading;
            @Heading.performed -= instance.OnHeading;
            @Heading.canceled -= instance.OnHeading;
            @NextEntity.started -= instance.OnNextEntity;
            @NextEntity.performed -= instance.OnNextEntity;
            @NextEntity.canceled -= instance.OnNextEntity;
            @Cursor.started -= instance.OnCursor;
            @Cursor.performed -= instance.OnCursor;
            @Cursor.canceled -= instance.OnCursor;
            @CursorPosition.started -= instance.OnCursorPosition;
            @CursorPosition.performed -= instance.OnCursorPosition;
            @CursorPosition.canceled -= instance.OnCursorPosition;
            @ClearSelection.started -= instance.OnClearSelection;
            @ClearSelection.performed -= instance.OnClearSelection;
            @ClearSelection.canceled -= instance.OnClearSelection;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Intercept.started -= instance.OnIntercept;
            @Intercept.performed -= instance.OnIntercept;
            @Intercept.canceled -= instance.OnIntercept;
            @Create100.started -= instance.OnCreate100;
            @Create100.performed -= instance.OnCreate100;
            @Create100.canceled -= instance.OnCreate100;
        }

        public void RemoveCallbacks(IEntitiesActions instance)
        {
            if (m_Wrapper.m_EntitiesActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IEntitiesActions instance)
        {
            foreach (var item in m_Wrapper.m_EntitiesActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_EntitiesActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public EntitiesActions @Entities => new EntitiesActions(this);

    // Graph
    private readonly InputActionMap m_Graph;
    private List<IGraphActions> m_GraphActionsCallbackInterfaces = new List<IGraphActions>();
    private readonly InputAction m_Graph_Create;
    private readonly InputAction m_Graph_Destroy;
    public struct GraphActions
    {
        private @GameInputs m_Wrapper;
        public GraphActions(@GameInputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Create => m_Wrapper.m_Graph_Create;
        public InputAction @Destroy => m_Wrapper.m_Graph_Destroy;
        public InputActionMap Get() { return m_Wrapper.m_Graph; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GraphActions set) { return set.Get(); }
        public void AddCallbacks(IGraphActions instance)
        {
            if (instance == null || m_Wrapper.m_GraphActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_GraphActionsCallbackInterfaces.Add(instance);
            @Create.started += instance.OnCreate;
            @Create.performed += instance.OnCreate;
            @Create.canceled += instance.OnCreate;
            @Destroy.started += instance.OnDestroy;
            @Destroy.performed += instance.OnDestroy;
            @Destroy.canceled += instance.OnDestroy;
        }

        private void UnregisterCallbacks(IGraphActions instance)
        {
            @Create.started -= instance.OnCreate;
            @Create.performed -= instance.OnCreate;
            @Create.canceled -= instance.OnCreate;
            @Destroy.started -= instance.OnDestroy;
            @Destroy.performed -= instance.OnDestroy;
            @Destroy.canceled -= instance.OnDestroy;
        }

        public void RemoveCallbacks(IGraphActions instance)
        {
            if (m_Wrapper.m_GraphActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IGraphActions instance)
        {
            foreach (var item in m_Wrapper.m_GraphActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_GraphActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public GraphActions @Graph => new GraphActions(this);
    public interface ICameraActions
    {
        void OnYaw(InputAction.CallbackContext context);
        void OnPitch(InputAction.CallbackContext context);
        void OnRTSView(InputAction.CallbackContext context);
        void OnMovement(InputAction.CallbackContext context);
        void OnTouchUpAndDown(InputAction.CallbackContext context);
    }
    public interface IEntitiesActions
    {
        void OnSpeed(InputAction.CallbackContext context);
        void OnHeading(InputAction.CallbackContext context);
        void OnNextEntity(InputAction.CallbackContext context);
        void OnCursor(InputAction.CallbackContext context);
        void OnCursorPosition(InputAction.CallbackContext context);
        void OnClearSelection(InputAction.CallbackContext context);
        void OnMove(InputAction.CallbackContext context);
        void OnIntercept(InputAction.CallbackContext context);
        void OnCreate100(InputAction.CallbackContext context);
    }
    public interface IGraphActions
    {
        void OnCreate(InputAction.CallbackContext context);
        void OnDestroy(InputAction.CallbackContext context);
    }
}
